In [1]:
scores = [3.0, 1.0, 0.2]

import numpy as np

In [4]:
x = np.asarray(scores)

In [5]:
print x

[ 3.   1.   0.2]


In [12]:
print np.sum(x)

4.2


In [13]:
scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])

In [17]:
print np.sum(scores,1)

[12 17 24]


In [22]:
print np.transpose(scores)

[[1 2 3]
 [2 4 8]
 [3 5 7]
 [6 6 6]]


In [31]:
print np.asarray(map(lambda x: 1/float(x), np.sum(scores,1)))

[ 0.08333333  0.05882353  0.04166667]


In [70]:
A = vfunc(scores)
B = np.asarray(map(lambda x: 1/float(x), np.sum(A,0)))
print A
print B

[[  2.71828183e+00   7.38905610e+00   2.00855369e+01   4.03428793e+02]
 [  7.38905610e+00   5.45981500e+01   1.48413159e+02   4.03428793e+02]
 [  2.00855369e+01   2.98095799e+03   1.09663316e+03   4.03428793e+02]]
[ 0.0331204   0.00032863  0.00079043  0.00082625]


In [33]:
A.dot(B)

array([ 0.32598039,  0.73529412,  0.83578431,  1.10294118])

In [36]:
import numpy.matlib

In [72]:
BB = np.matlib.repmat(B,  A.shape[0],1)
print BB

[[ 0.0331204   0.00032863  0.00079043  0.00082625]
 [ 0.0331204   0.00032863  0.00079043  0.00082625]
 [ 0.0331204   0.00032863  0.00079043  0.00082625]]


In [73]:
np.multiply(A,BB)

array([[ 0.09003057,  0.00242826,  0.01587624,  0.33333333],
       [ 0.24472847,  0.01794253,  0.11731043,  0.33333333],
       [ 0.66524096,  0.97962921,  0.86681333,  0.33333333]])

In [56]:
 vfunc = np.vectorize(exp)

In [54]:
from math import exp, expm1

In [111]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    import numpy.matlib
    from math import exp, expm1
    scores = np.asarray(x)
    vfunc = np.vectorize(exp)
    A = vfunc(scores)
    sums = np.sum(A,0)
    if type(x) == list or type(sums) !=numpy.ndarray:
        ret = map(lambda y: exp(y)/sums, x)
    else:
        B = np.asarray(map(lambda x: 1/float(x), sums))
        BB = np.matlib.repmat(B,  A.shape[0],1)
        ret = np.multiply(A,BB)
    return ret
    

In [112]:
scores = np.asarray([3.0, 1.0, 0.2])
scores = np.asarray(x)
vfunc = np.vectorize(exp)
A = vfunc(scores)
sums = np.sum(A,0)
print sums
softmax(scores)

24.0252215098


[0.8360188027814407, 0.11314284146556011, 0.050838355752999158]

In [113]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [118]:
scores = np.asarray([30, 10, 2])

softmax(scores)

array([  9.99999998e-01,   2.06115362e-09,   6.91440009e-13])

In [115]:
scores = np.array([[1, 2, 3, 6],
                   [2, 4, 5, 6],
                   [3, 8, 7, 6]])
softmax(scores)

array([[ 0.09003057,  0.00242826,  0.01587624,  0.33333333],
       [ 0.24472847,  0.01794253,  0.11731043,  0.33333333],
       [ 0.66524096,  0.97962921,  0.86681333,  0.33333333]])

In [116]:
np.sum(np.exp(scores), axis=0)

array([   30.19287485,  3042.94519317,  1265.13185445,  1210.28638048])